### ISSUE TITLE
index out of range on edit submenu

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#109]
http://forum.kodi.tv/showthread.php?tid=234547&pid=2166157#pid2166157

To be fixed on some rainy day..

**Comment by ghost** [comment]
This shouldn't be happening (unless its skin-specific - I haven't tested with Titan) - when all shortcuts are deleted, an 'empty' shortcut should always be created, and all shortcuts displayed should go through the _display_listitems() function, which will add the skinshortcuts-orderindex property... :confused:
