### ISSUE TITLE
request: option to hide shortcut

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#127]
http://forum.kodi.tv/showthread.php?tid=205482&pid=2216301#pid2216301

**Comment by ghost** [comment]
A very common request, and one I read very regularly on the Nox 5 mods, where the unmodded skin offers this function. I've always been very reluctant to add this, though, as either it only works for one skin (the setting isn't shared between skins), or all skins need to implement the 'hide' button. Having said that...

I'm unhappy with how complicated the management dialog has become in my own skin and was thinking through ways to simplify it a bit - the best one I came up with was moving some functions (delete, change label being obvious candidates) to a context menu. This function could also live very happily there.

I'm going to try to spend some time later in the week adding the hooks needed for a context menu, and if you don't object, will look into adding this function as part of all of that.

**Comment by marcelveldt** [comment]
great idea about the context menu! That will indeed clean the editor up

**Comment by ghost** [comment]
I've been thinking through the various behaviours of a context menu for the last week or so and am still struggling on a couple of points - most notably when and when not to automatically add controls that aren't in the management dialog to a context menu (the new 'hide' button you'd need automatically added; select widget you wouldn't want to be added automatically, for example.) I normally wouldn't start coding something like this until I had got it all clear in my head, so - if it doesn't all fall into place whilst it's being coded - may need to pick your brains when it comes to actually getting the UX and the api correct :)
