### ISSUE TITLE
BUG: shortcuts to music hidden

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#154]
@Ignoble, I'm getting more and more reports of users complaining about the missing shortcuts to the Music library if no library content is added. I know this was once by design but I think it's time for a change and just make it show all the time because this is starting to get really confusing since the changes in Jarvis.

I even ran into it myself a couple of days ago where I couldn't understand why the shortcut to music kept dissapearing from the main menu when I did not yet scan in my music library.

A couple of posts...

http://forum.kodi.tv/showthread.php?tid=261070&pid=2255976#pid2255976
https://github.com/marcelveldt/skin.titan/issues/188

What do you think of just showing the shortcuts and let the users decide they want to delete it instead of applying some conditions that are not known to the user ?

**Comment by ghost** [comment]
Sounds good to me. I've been getting similar reports (though primarily about music add-ons, perhaps unsurprisingly for people who don't have music in their library). I think that with supporting multiple versions of Kodi in one version of the script, and with the way that music shortcuts have changed, the code has just got too complex with music visibility. Much easier to strip it :+1:

**Comment by marcelveldt** [comment]
OK, great, should I go ahead and do that or are you working on some major code changes ?

**Comment by ghost** [comment]
Major code changes? Always ;) But not related to this, and nothing that can't wait to go in.

Actually, I say that but I suspect Tomer would like the new set-properties-from-outside-of-the-Management-Dialog to go in, but it's not quite ready yet (needs url-decoding and a second eye going over it). I can rush the necessary code changes there if you can give it an eye?

**Comment by marcelveldt** [comment]
Rushing is never good, it always makes me run into problems ;-)
Offcourse I want to take a look but such a change would require some beta testing for a few days at least before we go stable with it.

Best thing would be to do the repo push based on a tag so the changes can be merged.
Tomer uses his own repo so 'shouldn't be that much of a problem to him

**Comment by ghost** [comment]
To be honest, I can see some unicode issues ahead with it, and they always take me some time to fix so you're right, let's not worry about it right now. I'll keep with what I said to him on the forum, which is I'll finish it up tomorrow and get it merged for repo push +1

**Comment by ghost** [comment]
Anything else needed from your side before repo push, or can I go ahead and create a tag so I can merge Tomer's new code when its ready?

**Comment by marcelveldt** [comment]
Nope, all is fine. OK to create the tag so I can do the repo push later today
