### ISSUE TITLE
Warn on altering shortcut function

### ISSUE THREAD

**Issue by MikeSiLVO** [BigNoid/script.skinshortcuts#189]
@Ignoble61 I am playing around with the warning function and noticed a couple of things. 

The first is that disable does not trigger the warning dialog and I think it should do so since that will prevent access to the shortcut also.

The last thing is completely trivial but felt worthy of a mention and that is if you cancel the requested change (pressing No in DialogConfirm) it triggers a menu rebuild even though nothing was changed. Not sure if that is necessary due to how the script recognizes changes in the management dialog.

Thank you and I hope all is well Sir Super Grandpa Bob :smiley:

**Comment by ghost** [comment]
Agree, disabling should trigger the warning dialog.

I presume you mean that when deleting an item and cancelling on the warning, a menu rebuild is triggered? There's a single line that needs to removed to fix that (1110), but if it's happening elsewhere let me know.

I'll try and push fixes for both issues this week, and thanks for the bug report :)

**Comment by MikeSiLVO** [comment]
@Ignoble61 Yes seems to be only when selecting delete. 

I noticed another little thing...
I am using String.IsEqual(Window.Property(groupname),mainmenu) as visible for Icons layout of main menu and it goes empty on context menu popup and filebrowser open when choosing an Icon. Is there a better visible I can use to prevent that but still limit it to the main menu only?

**Comment by ghost** [comment]
I don't believe so, but you could try specifying the window:-

`String.IsEqual(Window(script-skinshortcuts.xml).Property(groupname),mainmenu)`

**Comment by MikeSiLVO** [comment]
Just tried and it doesn't seem to work if I specify the window. No biggie... can't make everything perfect no matter how much I want it to be :wink:

Thank you for the suggestion :smiley: 

Edit: It does work as condition for context menu button though just not 100% as visible in the management dialog.
