### ISSUE TITLE
PVR channels widget doesn't work anymore

### ISSUE THREAD

**Issue by mac1202** [BigNoid/script.skinshortcuts#193]
Hi I use latest krypton from git and mimic skin. If I correctly understand the widget part is managed by your addon. The problem I had is with recent git version of krypton the PVR channel widget stop working it just display nothing. The strange thing is the PVR channel with artwork widget is working perfectly.

**Comment by ghost** [comment]
The script doesn't provide any widgets, it just enables you to choose from several. If I remember correctly, most of the PVR widgets are provided by the Skin Helper Service script.

**Comment by mac1202** [comment]
Ok will report there.
Thanks for your answer.
