### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by londonshore** [BigNoid/script.skinshortcuts#204]
your new update messed up my kod
i submenu using nebula skin 

please fix or get me away to delete it .. i have to have my updates set to notify because i can not delete the repository this is a biggggggggggg issue 

please send out another version with the v12 is not good for jarvis 16.1

**Comment by ghost** [comment]
Manually install the git version (where it is already fixed), [or this zip](https://github.com/Ignoble61/repo.ignoble.data/raw/master/data/script.skinshortcuts/script.skinshortcuts-1.0.13.zip) (which can be installed via 'Install from zip file' within Kodi, unlike a regularly downloaded zip from GitHub). This version will be pushed to the repo when I have enough confirmation that it fixes the issue (I have one report so far that indicates it may cause other issues).

In this case it's a known issue, but if you are reporting an issue (or if the update doesn't work) then a debug log is needed.
