### ISSUE TITLE
Request: 211 Click

### ISSUE THREAD

**Issue by fastcolors** [BigNoid/script.skinshortcuts#211]
HI,

first of all Thanks for this great addon!

I was wondering if it would be possible to control the clicks for list 211,

my use case is the following:

I have 211 in a panel, so for items not on row 1,  it's impossible to reach group 300 (which is on top in my case)

since clicking on items on 211 doesn't have any effect, I was wondering if it couldn't move focus to group 300. 

I've tried tomato it happen adding an onclick to panel, but since it has no <content> it doesn't work.

in alternative to coding the action at your level, is there a "list" I can use in <content> that if filled with items for 211 ? 
such as for instance : <include>skinshortcuts-mainmenu_211</include>

hope it makes sense, thanks!

**Comment by ghost** [comment]
> I've tried tomato it happen

First of all, this is a wonderful auto-correct :grin:

> I was wondering if it would be possible to control the clicks for list 211

I'm surprised that adding an `<onclick />` to the control doesn't work, but can see you're right. It's easy enough to add a new override for this - can you [please test this branch](https://github.com/Ignoble61/script.skinshortcuts/tree/actions), with the following added to your overrides.xml (obviously adjusted to suit your personal use case)

`<onclick id="211">SetFocus(401)</onclick>`

> in alternative to coding the action at your level, is there a "list" I can use in that if filled with items for 211 ?
> such as for instance : skinshortcuts-mainmenu_211

Not sure I fully understand this but, if I do then no, there's not.

**Comment by fastcolors** [comment]
> I've tried tomato it happen
> First of all, this is a wonderful auto-correct 😁

hahahahahahah 😂😂😂😂😂😂😂
tometo..tomato...

perfect! works like a charm... this way I could do what I want with the click.. right?
me like this.

thanks and... TOMATOS!

cheers.

**Comment by fastcolors** [comment]
just one question...

`<onclick id="211">ActivateWindow(contextmenu)</onclick>`

opens the contextmenu.. but an empty one..

am I (probable) doing some nonsense call?

**Comment by ghost** [comment]
Thanks for testing. I'll clean it up and merge it tomorrow.



> just one question...
> 
> <onclick id="211">ActivateWindow(contextmenu)</onclick>
> 
> opens the contextmenu.. but an empty one..
> 
> am I (probable) doing some nonsense call?

Yes, there's no way tomato that work in that way - Skin Shortcuts intercepts the ContextMenu action and takes care of displaying the context menu itself. It's possible you could do something like

`<onclick id="211">Action(ContextMenu)</onclick>`

but I've shut down computers for the evening so can't test. (Note Skin Shortcuts context menu feature is Krypton only)

**Comment by fastcolors** [comment]
perfect I'll give it a spin!!

but I can definitely live without the need tomato it work !

the click control is already what I needed!! then I got greedy and wanted the tomato AND the soup!

BTW: I'm loving this conversation!
😂

**Comment by fastcolors** [comment]
Almighty Tomato it works!!!
it works!!!

awesome job!!

**Comment by ghost** [comment]
Now in master :)
