### ISSUE TITLE
Why Titan for Krypton still using an old PVR setting reference?

### ISSUE THREAD

**Issue by burekas7** [BigNoid/script.skinshortcuts#237]
@marcelveldt 

Why in few files this old PVR request setting still exist?
**System.GetBool(pvrmanager.enabled)**

While the current and the only request since kodi 17 (Krypton) is this:
**System.HasPVRAddon**

The reason is because I found this error line in the log repeats many many times (Debug mode) especially when I am in the home screen:
**DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.**

Any leftovers of System.GetBool(pvrmanager.enabled) should be removed.

I found them in these files:
• \Kodi\addons\skin.titan.kryptonbeta\1080i\script-skinshortcuts-includes.xml 
(When I'm trying to edit this file, it always back to the previous content again as explained here: https://github.com/BigNoid/script.skinshortcuts/blob/master/resources/docs/FAQ.md#changes-to-script-skinshortcuts-includesxml-are-overwritten )
• \Kodi\addons\skin.titan.kryptonbeta\shortcuts\1038.DATA.xml
• \Kodi\addons\skin.titan.kryptonbeta\shortcuts\mainmenu.DATA.xml
• \Kodi\addons\script.skinshortcuts\resources\shortcuts\overrides.xml (for version 13)

Can someone check this?

https://forum.kodi.tv/showthread.php?tid=328621
***
By the way, in Titan skin this file: script-skinshortcuts-includes.xml 
still holding old data  and leftovers from previous changes that I made in the menu shortcuts which no longer exist, and when I'm checking the debug log, I'm seeing that it's still directing to them in the background.

How can I edit this file? Instead from the shortcuts editor in the skin, that seems that it doesn't remove old shortcuts data.

Thanks

**Comment by marcelveldt** [comment]
these are just leftovers because you migrated your skinshortcuts settings from previous Kodi versions. Only proper way to get rid of it is to clear the shortcuts and start over.

**Comment by burekas7** [comment]
I found another way by using the backup/restore system.
More details here:
https://forum.kodi.tv/showthread.php?tid=328621&pid=2714782#pid2714782

Thanks.
