### ISSUE TITLE
Several nodes not showing up in management dialog

### ISSUE THREAD

**Issue by jeroenpardon** [BigNoid/script.skinshortcuts#3]
Following up on reports in my skin thread I have found that several of my custom shortcuts and certain nodes were not available in the management dialog anymore. 

I use a custom grouping, [example](https://github.com/jeroenpardon/skin.refocus/blob/master/shortcuts/overrides.xml)

Simplified example:

```
<node label="example">
    <content>video</content>
</node>
```

will list all the available video related nodes correctly.

But using any of these nodes will not display anything.

```
<content>movie</content>
<content>tvshow</content>
<content>musicvideo</content>
<content>customvideonode</content>
```

The contents of these nodes are all available in the video node, with the exception of customvideonode of course. But I highly prefer to split it all up for various reasons mainly for better organization and integration of my custom shortcuts.

I'm completely sure these were working before. I'm not sure what is causing it, but as there has hardly been any changes to the script since Unfledged left, I suspect some sort of incompatibility with Helix?

See section 5 in AdvancedUsage.txt

Happy to provide any additional info.

**Comment by jeroenpardon** [comment]
pinging @phil65 (issues tab is closed at your repo)

Is there any other info I can provide?

**Comment by marcelveldt** [comment]
As I did some work in the skinshortcuts code I'll take a look if I can reproduce and fix.

**Comment by marcelveldt** [comment]
litterally from the code:

if content == "movie" or content == "tvshow" or content == "musicvideo" or content == "customvideonode" or content == "movie-flat" or content == "tvshow-flat" or content == "musicvideo-flat" or content == "customvideonode-flat":
            # These have been deprecated
            return []

I will have a quick look if I can understand why it's deprecated (removed from the code) but I'm afraid there is a good reason for it. Your current approach is fine using the manual provided links, it's a bit of a pain I know but works as expected.

Why not use your custom groupings and add the full "videolibrary" all the way below in the list too ?

**Comment by marcelveldt** [comment]
@Ignoble61, I suspect we can update the readme's and initial overrides.xml without the flat groupings ?

**Comment by ghost** [comment]
@marcelveldt flat groupings are used when using controls 111 / 101 / 102 / 103 in management dialog. I suspect only Nox 5 + variants use them, but whilst they are in use the flat groupings need to remain in overrides.xml. The documentation is more nuanced - if these controls were to be earmarked for removal (they're the original method used to select a shortcut a very long time ago) then the docs could at the very least be updated to say that they are being deprecated ahead of removal. - unless you mean those groups are still listed in the docs or in the overrides.xml, in which case yes - they can and should be removed.

**Comment by ghost** [comment]
Sorry, haven't read this issue before - the content types referenced above were first deprecated when library.py was switched to use video nodes. It became very difficult to list movies/tvshows/etc separately, or even to know if they were actually in a users custom video nodes. They were removed shortly after.

**Comment by marcelveldt** [comment]
Aha, that's what I thought ;-)
So they are in fact deprecated ?

**Comment by ghost** [comment]
Not just deprecated, but removed ;) (They remain in the code purely to prevent a crash if a grouping still uses them)

**Comment by ghost** [comment]
@jeroenpardon - First off, great to see that reFocus is being updated for Jarvis. I'll be having a play this weekend, and will feedback on the forums how well its working. As regards this issue, are the nodes still causing you issues (and so can this issue be closed)?

**Comment by jeroenpardon** [comment]
@Ignoble61 You can close this issue. My current implementation of skin.shortcuts is quite old and I am currently trying to catch up and rework my implementation. Because of this I am not able to fully determine if and where I'll have any issues at the moment. I need to get acquainted with the changes in groupings and so on first. Cheers.

**Comment by ghost** [comment]
OK. If you need any assistance updating the implementation or have any questions, just holler.
