### ISSUE TITLE
safety check when writing includes file

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#38]
As reported by Ronie on the Kodi forums, a race condition occurs when writing the script-skinshortcuts-includes.xml file.

http://forum.kodi.tv/showthread.php?tid=178294&pid=2074446#pid2074446

When writing the file, a safety check should be done if the skin directory hasn't changed since the menu build started. 

The issue happens when you launch a skin that utilizes the skinshortcuts script, the menu building starts working and in the meanwhile you switch to another skin.

Offcourse this issue would be gone as soon as the recent changes hit the repo (as the menu build time has been improved to almost zero) but still this safety check would be good.

**Comment by marcelveldt** [comment]
I can take a look at this tomorrow if nobody beats me to it.

**Comment by marcelveldt** [comment]
haha, you're fast :-)

**Comment by ghost** [comment]
Saw the issue on a trawl-through the forum :) Change referenced above saves the skin dir when the script is started, and then saves to that directory - so changing skin won't affect where the file is saved to. Would be good to get Ronie to confirm she's happy with the fix.
