### ISSUE TITLE
Problems with ListItem.Property(hasSubmenu)

### ISSUE THREAD

**Issue by jeroenpardon** [BigNoid/script.skinshortcuts#4]
I am using this property to check whether or not a main menu item has a submenu tied to it. If it has I show an arrow/greater than sign next to the main menu item to make it clear there is a submenu (the submenu is hidden until the main menu item is clicked).

```
<control type="group">
    <left>20</left>
    <control type="label">
        <width>260</width>
        <height>55</height>
        <font>condensed_HomeSmall</font>
        <textcolor>Color3</textcolor>
        <label>$INFO[ListItem.Label]</label>
        <visible>IsEmpty(ListItem.Property(isSubmenu))</visible>
    </control>
    <control type="label">
        <width>260</width>
        <height>55</height>
        <font>condensed_HomeSub</font>
        <textcolor>Color3</textcolor>
        <label>$INFO[ListItem.Label]</label>
        <visible>!IsEmpty(ListItem.Property(isSubmenu))</visible>
    </control>
    <control type="label">
        <right>20</right>
        <width>20</width>
        <height>54</height>
        <label>›</label>
        <font>regular</font>
        <align>right</align>
        <textcolor>Color3</textcolor>
        <visible>!IsEmpty(ListItem.Property(hasSubmenu))</visible>
        <visible>!StringCompare(ListItem.Property("submenuVisibility"),Window(10000).Property("submenuVisibility") )</visible>
    </control>
</control>
```

This was working fine, and the code in my skin for this has not changed in months, basically since implementing skin shortcuts. But now, the arrow symbol is always shown.

If I change the main menu's infolabel to 

```
$INFO[ListItem.Property(hasSubmenu)]
```

It does returns "True" or "False", so the value is getting set...

I tried checking for the value

```
<visible>!StringCompare(ListItem.Property(hasSubmenu),True)</visible>
```

but it doesn't make a difference, under all circumstances my main menu item's are showing the arrow symbol regardless of whether there's a submenu.

**Comment by jeroenpardon** [comment]
Just found out using a SubString instead of StringCompare works... no idea why, a StringCompare should work when the value is matched completely?

**Comment by BigNoid** [comment]
Its `ListItem.Property(submenuVisibility)` without the qoutes. It explains why substring does work and stringcompare doesnt in any case :)

**Comment by jeroenpardon** [comment]
I believe that `ListItem.Property("submenuVisibility")` only has to do with checking whether the submenu itself is actually visible or not (so that the arrow symbol is only shown when the submenu is not activated). 

It's something Unfledged coded in (including the quotes), more or less specifically for reFocus, to deal with the vertical menu I use as it has both the main menu items and submenu items in one container. Removing the quotes doesn't stop that part from working, so I removed them anyway.

But in any case, removing the quotes from that property (and keeping stringcompare) doesn't change the problem with the arrow symbol always showing.

**Comment by BigNoid** [comment]
I can only comment on the code you posted. I use that listitem property without the qoutes in my skin. It seems the window property is not set by the script (only clearing is done by the script). Do you set that property in the skin?

@phil65 you are more qualified to look at the script then me, mind taking a look at this?

I don't understand this line `!StringCompare(ListItem.Property("submenuVisibility"),Window(10000).Property("submenuVisibility") )``

You are checking if your main menu submenuVisibility property is the same as the window property + a space.

**Comment by jeroenpardon** [comment]
@BigNoid No, I'm not setting that property in the skin code.

I am using this though: `<onleft>RunScript(script.skinshortcuts,type=hidesubmenu&amp;mainmenuID=9000)</onleft>`

Which I think is related as it takes care of "collapsing" the menu, hiding the sub menu items. Not sure if it's relevant to the question but thought I'd mention it.

**Comment by marcelveldt** [comment]
Hi Jeroen,
be carefull with using ListItem.Property(hasSubmenu) because it will return true even if there are no visible items in the list. Items in the list can have visibility conditions.

The best way to do this is count the number of items in the container containing your submenu.
So, with "IntegerIsGreaterThen".

I had some issues with this too and switched to just counting the number of items instead and that works fine. If you want take a look at my Titan code, I have some logic in there to hide/show the submenu which also works fine with touchdevices.

Regards,

Marcel

**Comment by jeroenpardon** [comment]
Hey Marcel, in my case that wouldn't really work as my main menu and submenu items are in the same container and thus share the same ID. At least, in the vertical version of my home menu.

Actually that property's function isn't to check whether the submenu items are visible, but if the main menu item has submenu items configured, regardless of whether they are visible or not. It was added for a menu like I am using where main menu items and submenu items are in the same container. Without it that wouldn't be possible.

(Think of my menu as a folder tree view with the branches expanding / collapsing)

**Comment by marcelveldt** [comment]
@jeroenpardon, do you still need help on this matter ? I kind of forgot to answer your question, sorry
