### ISSUE TITLE
Script's main window multiple instances

### ISSUE THREAD

**Issue by Nessus85100** [BigNoid/script.skinshortcuts#40]
Accidentally the other day i push the button to open script's main window twice and i notice that the window was open twice. Tested again and it turns out that the window is opening so many times how many times the window opens so many times as the times you manage to click before the first instance is open. I manage to do that for 6 times in my testing.

Is this a bug or the multiple instances have some purpose ?

Cheers
Nessus

**Comment by ghost** [comment]
Multiple instances are required, for example, to edit the submenu/additional menu's from the main menu customisation window. However, what you describe is certainly unintended behaviour. Possible fixes could be to use a window property to mark when the customisation window is loading so a second instance isn't started, or maybe show a busy dialog (and so lock the gui) until the window has loaded.

**Comment by Nessus85100** [comment]
Well, i just report it in case that it was a missed bug but as this is needed then i have no problem with it (first time i noticed in all the time i use and testing the script) and no user reported as an issue. So, no issue here.

Cheers
Nessus

**Comment by ghost** [comment]
It's worth leaving this open. The script needs the ability to have multiple management dialog windows open, it's true, but the behaviour you describe is unwanted and should be able to be fixed.
