### ISSUE TITLE
Issue with widget-groupings

### ISSUE THREAD

**Issue by Nessus85100** [BigNoid/script.skinshortcuts#42]
I am pretty sure that i am doing something wrong here but i have a problem with widget-groupings and the new way of assigning widgets. I am trying to use the `<widget-groupings>` so to group all of my skin's widgets to custom nodes. The problem is that the `widgetName` property is always empty for my skin's widgets. When i assign a widget from the default libraries nodes they are showing fine. Also for some weird reason the Smartish script widgets are not showing in the select dialog (the script is installed fine of course).

This is my `<widget-groupings>` code... http://pastebin.com/g4mPPeQs

What am i doing wrong here ?

**Comment by ghost** [comment]
See #41 - specifically:- 
- Fix widgetName for `<shortcut />` elements

Smart(ish) widgets won't automatically show up in the dialog (nor will library data provider widgets). For Smart(ish) it needs a change in that script. For both, this script needs to have some work done on how add-ons are loaded and processed, which will probably happen in a later version (as I'm not sure how to approach this yet, and probably won't be until I update smart(ish) which won't be soon as I'm moving onto a different project next)

**Comment by ghost** [comment]
Y'know, I forget I have commit rights to this repository these days (and I'm confident in my fixes), so let me get that fix merged into master so you can test and - please - report any more issues :)

**Comment by Nessus85100** [comment]
Library data provider widgets are showing fine. If the Smartish widgets are not show up ATM, if i put the code now in overrides.xml and the script gets updated, they will work without any change in overrides code ?

**Comment by ghost** [comment]
Sorry, hadn't taken a look at your widget-groupings You've got the ID wrong for the Smart(ish) widgets in the condition and the path - should be `service.smartish.widgets`, not `service.smartish.shortcuts` :)

(Thought you meant why aren't they showing up under Add-ons > Video Add-ons!)

**Comment by Nessus85100** [comment]
Ah... crap. I messed up with search&replace :grin:
Thanks
