### ISSUE TITLE
Script broken on Python 2.6

### ISSUE THREAD

**Issue by ghost** [BigNoid/script.skinshortcuts#49]
Sorry, I don't have time to fix this myself at the moment (not even meant to be using the internet, but modern phones are a wonderful thing!), but a note on recent changes. Using xpath with elementtree is not supported with Python version 2.6, so using it is breaking the script on systems with that Python version (see logs on fTV skin thread, for example)

E.g. `if not newelement.findall(".//property[@name='path']"):` will cause a script crash on systems using that Python version.

**Comment by marcelveldt** [comment]
Oops, didn't know that. Thanks for the catch!
Will fix it right away
