### ISSUE TITLE
update the script on kodi repo ?

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#5]
Hi guys,
It just occured to me while working on some problem reports that the changes that I submitted to fix in the skin never got updated on the repo.
Would it be possible to publish this to repo because now users are not able to select a thumbnail for their shortcuts which causes confusion.

If you want I can ask Martijn myself to do a pull from here.

Thanks!

marcel

**Comment by BigNoid** [comment]
Sent a PR, thx.
