### ISSUE TITLE
Unable to build menu

### ISSUE THREAD

**Issue by thegreatdan** [BigNoid/script.skinshortcuts#6]
I need your support. My OpenElec @ rPi2 keeps showing up this issue:
http://xbmclogs.com/pgo5xlowi

When browsing in main menu a popup pops up and tells "Failed to write menu".

I don't have a clear view what might cause this behavior, could you help?

**Comment by BigNoid** [comment]
I have pi2 with openelec myself and have no problems. Only difference in your log is that yours shows a custom path to the python libs. i'd start looking there.
