### ISSUE TITLE
FR: Make program plugins browsable as widgets

### ISSUE THREAD

**Issue by ghost** [BigNoid/script.skinshortcuts#65]
As (indirectly) requested to tomer953 on the Kodi forums, add the ability for program add-ons which present as plugins (but don't present as video/audio/picture addons) browsable and selectable as widgets.

Required changes:-
- New `<content />` grouping - addon-program-plugins(?), and the relevant plugins loaded into it in the addons function in library.py
- Generate widget properties for program plugins, within the explorer function of library.py

**Comment by marcelveldt** [comment]
I think this one can be closed ?

**Comment by ghost** [comment]
Hmmm ... it should have been auto-closed when #67 was merged. Oh, well :) Yes, it can be closed.
