### ISSUE TITLE
Provide option to reset current shortcut only

### ISSUE THREAD

**Issue by jingai** [BigNoid/script.skinshortcuts#75]
Having the ability to reset all of them back to defaults is definitely useful, but if a user has modified their shortcuts extensively and just needs to reset one (because they decided they wanted to revert it to default behavior, but forgot how to achieve that, for instance), there is currently no (easy) way for them to do that without dumping all of their other modifications as well.

**Comment by marcelveldt** [comment]
That would be a horrible idea... A user can for example move items around etc.
There will no longer be such a thing as a default becaus ethe user might also have changed the entire shortcut.

What is possible however is if you have setup all kinds of properties/backgrounds etc on a shortcut you can reset those. You can already do such a thing in your skin by using some vars/conditions on a button and the setproperty method.

**Comment by ghost** [comment]
Not what was originally requested (as I agree with @marcelveldt that this would be a horrible idea from a UX perspective - I haven't reset my working system for a year-and-a-half, and would have no idea what those shortcuts would now reset to!), but one of the requests included in #81 may cover the original intent of this request - GUI 308 now gives the option to restore one of the originally supplied shortcuts.
