### ISSUE TITLE
Hides Music mainmenu shortcut by default if library has no Music content

### ISSUE THREAD

**Issue by jingai** [BigNoid/script.skinshortcuts#76]
The script adds the following visibility condition by default:

```
<visible>Library.HasContent(Music)</visible>
```

This makes it so the user cannot add any Music sources if they don't already have any.

**Comment by ghost** [comment]
The script follows Confluence's example here. Confluence uses ActivateWindow(Music) for it's main menu item (which can activate either the library or files view), so the script doesn't apply any visibility conditions to that. In fact the only time it should add them for a Music entry is when the action is to ActivateWindow(MusicLibrary...) or a library node - something that does require music in the library to be usable.

If there are any specific cases that aren't working, let us know. Or you can review the visibility conditions the script adds and suggest any changes - https://github.com/BigNoid/script.skinshortcuts/blob/master/resources/lib/datafunctions.py#L642 - :smile:

**Comment by jingai** [comment]
I can change it, but honestly, it shouldn't add visibility conditions on its own imho.   At least, not if it's not documented.

**Comment by ghost** [comment]
It caused a lot of support issues when there were no visibility conditions (from end users not knowing why shortcuts that should have been hidden didn't work), so I think it's the right choice to add them. However, you're absolutely right it should be documented, and I'll ensure it is in future.

**Comment by jingai** [comment]
You are tying yourself to Confluence though.  This is what I meant previously about having doubt about things with this script.  If it's going to auto-add stuff that I don't know about..

**Comment by jingai** [comment]
Video and Music need to always be, by default, visible.  Otherwise people cannot add sources to the library.  Why do you think it shouldn't be that way?

**Comment by ghost** [comment]
Because, as said above, when visibility conditions weren't added, users were getting confused that shortcuts - links to the music library (rather than the files view) when they didn't have any music, for example - didn't function as they expected.

Of course, this isn't up to me, so I'll open the floor to anyone else who has a POV on this :)

**Comment by jingai** [comment]
Video and Music should never have scripted visibility imho.

edit:  at least on the mainmenu.

**Comment by jingai** [comment]
IIRC, @MacGyverr was also having issues similar to this with the PVR stuff.

**Comment by jingai** [comment]
I do understand how people can get confused, but it's even worse if they can't even add the source.

It's also just the nature of letting people edit everything.  I don't look forward to the support requests for my skin by adding this lol.

**Comment by marcelveldt** [comment]
Well, in that case don't use it. This script is used in almost every official repo skin and I have not ever seen a complaint about the visibility condition. 

BTW: Skinners can provide their own mainmenu (including conditions) with their skin so you can have it just the way you (or your users) want it.

**Comment by jingai** [comment]
Being fixed with #154
