### ISSUE TITLE
Video playlists widgets "target" tag is empty

### ISSUE THREAD

**Issue by Nessus85100** [BigNoid/script.skinshortcuts#77]
The `<content target="" />` is empty when a video playlist (.xsp) is selected as widget. This causes dead click/select item when the playlist has not playable items (eg TV Shows).
For Music playlists is set fine.

EDIT:
Also i notice that for the video playlists the `<property name="widget">` is set little different:
`<property name="widget">::PLAYLIST::</property>`

Fro the music playlists is like this: 
`<property name="widget">Playlist</property>`

Thanks
Nessus

**Comment by ghost** [comment]
I can't reproduce this. Setting a widget to both a custom playlist and a skin-provided playlist sets the widget and widgetTarget properties as expected.

**Comment by Nessus85100** [comment]
Turns out that the widgetTarget property it's empty only for playlists defined in overrides.xml. I have a separate node in my overrides.xml file in where i have included the default playlists (`<content>playlist-video</content>`) plus some extra provided by the skin. This is how my playlist node looks with one of the extra playlists and the defaults ones : 

```
<node label="136">
  <node label="32004">
    <shortcut label="31245" type="32004" widget="::PLAYLIST::" icon="DefaultVideoPlaylists.png" widgetType="tvshows" condition="Library.HasContent(tvshows)">special://skin/extras/playlists/KidsTVShows.xsp</shortcut>
    <content>playlist-video</content>
  </node>
  <node label="32005">
    <content>playlist-audio</content>
  </node>
</node>
```

For every playlist that is defined like this here (eg "KidsTVShows.xsp") the widgetTarget property it's empty. Those that are provided by the `<content>playlist-video</content>` the widgetTarget property is set fine.

Thanks
Nessus

**Comment by ghost** [comment]
That's because you need to define widgetTarget in these cases - see wip docs here https://github.com/Ignoble61/script.skinshortcuts/blob/documentation/resources/docs/advanced/Custom%20groupings.md for details of the `<shortcut />` element.

(And it looks like the widget property is getting set to the widget element in your `<shortcut />` element - which is intended but I actually thought was broken....)

**Comment by Nessus85100** [comment]
Aha... didn't know that. So far all my other widgets are playable items or the onclick action is handled by the skin or by a script.

> (And it looks like the widget property is getting set to the widget element in your <shortcut /> element - which is intended but I actually thought was broken....)

Yea it works fine. By the way can you think of any reason why i have set the widget property like that (::PLAYLIST::) and not like as simple string (Playlist) ?.... lol i know that is stupid to ask YOU about that but i am afraid that if i did that for reason and is not some c/p thing will cause other problems.

**Comment by ghost** [comment]
It shouldn't cause any issues as far as I can tell. I'm not in a position to be able to double-check in the code, but I _think_ the widget attribute is literally only set as the widget property - nothing should change in how that shortcut is processed no matter what the widget attribute is set to.

**Comment by Nessus85100** [comment]
Ok, thanks a lot for the info.

Cheers
Nessus
