### ISSUE TITLE
Ready for release to stable?

### ISSUE THREAD

**Issue by ghost** [BigNoid/script.skinshortcuts#87]
There have been a few (comparatively minor) changes to the script which WIP skins are now reliant on - most notably to custom properties - and the forum thread has been remarkably quiet for a few days, so I wanted to open discussion on whether the script is ready for an update on repo.

AFAIK only one actual error has been reported (unicode issue, now fixed on git) with the current version, all other errors reported have ultimately proved to be user error. So script appears to be remarkably stable.

There are a number of WIP skins that are reliant on new functions of the script - most notably to custom properties. Changes made have been tested - and are comparatively minor - that I consider them at this point safe for repo.

Two changes are still needed before repo push - an update to stable (increase version to - I presume - 0.6.4; adjust readme/changelog to mark stable) and a change I proposed which tomer953 has said he will PR in the next day (it's again a very minor change, and I will be very surprised if it breaks anything).

One other change to consider as briefly discussed previously - though, as I've started to use the skin helper service, I'm increasingly very happy with how they are currently done - change the default widgets to use `<shortcut />` elements rather than relying on a 3rd party script.

Other than that, my impression is the script is stable enough and contains enough important updates to consider a repo update.

@marcelveldt - if it's agreed that a repo push is due, are you happy to lead it again?

Edit - It's also an opportunity to get a repo release in before Jarvis changes become necessary. From what I've read, a new shortcut for event log will be necessary, and with the music library + files views becoming combined, various changes will be needed here both to available shortcuts and to visibility conditions (which may even satisfy #76 ;))

**Comment by marcelveldt** [comment]
I think its ready for stable release. I am also going to push the skin helper service to repo because its embraced by a lot of skins already. Did you have a good test yet with the skinhelper? Spotted any errors?

**Comment by ghost** [comment]
TBH I've been primarily working on a non-Kodi app as of late, so haven't done much with the helper service other than use it to provide widgets and see how many skinners are responding so incredibly positively to it :) (genuinely, I haven't seen so many skinners be so positive about a script, well, ever!). My current plan is, when I'm finished with my Argus TV/iOS app, to apply it to my Conq mod which will be very telling for me as I only run that on a rPI which (due to its lack of power) I'm very sensitive to anything that eats up too much memory or uses too much CPU power. If there are any issues on those regards then, believe me, I'll be knocking on your door very quickly :)

**Comment by ghost** [comment]
As you agree we're ready for a stable release, are you happy to lead this again?

**Comment by ghost** [comment]
Should add, the one thing I did think about, but am not sure we should consider for the upcoming repo release - though please correct me if I'm wrong ;). Someone (sorry, genuinely can't remember who) posted a method for installing scripts on demand by calling via a runscript in the `<onclick />` when they weren't installed - which causes Kodi to offer to install them. It's worth considering extending the skin shortcuts script to allow 'default widgets' to install the skin helper service if it's not already installed, and extend the skin helper service to install the various widget providers in the same way.

As I say, this is probably not something to be considered before a current repo push, but with widget providers becoming an (indirect) requirement of the skin shortcuts script rather than the skin itself, and the helper service as a parent requirement of them, something definitely to be considered for the next release.

(Which is to say, skins wouldn't need to rely on either the skin helper service (though I suspect the vast majority will in the not-at-all-distant-future) or the various widget providers, but users could install them via the skin shortcuts script if and when they want to use them).

**Comment by marcelveldt** [comment]
haha, that someone was me ;-)

Nice idea about this btw. This will allow the users to select for theirselves which widget providers they want instead of having skins set them as requirement for their skin.

Let's think about this after a first release to the repo

**Comment by marcelveldt** [comment]
Oh, and thanks for the feedback about the skinhelper service. Yeah it's adopted very fast by skinners, I think it fills a little gap where native Kodi lacks some functionality. If I could write some C++ code myself I would have added it to the Kodi code but python is more in my league so my way of contributing to the community ;-)
I have developed it with speed in mind so info gets cached and uses as less power as needed. The only thing that is kind of heavy is the whole wall backgrounds generation but that's set by default to only run once.

**Comment by marcelveldt** [comment]
I will request the push to Kodi repo tomorrow for both scripts

**Comment by ghost** [comment]
I should have known it was you - there's few active scripters who would come up with something as creative as that ;)

Definitely needs thinking about after a repo release as, due to the nature of the script, it will require (probably quite significant) changes to the script to actually display updated items to the user after a script has been installed (I've no idea if the select dialog - pure Kodi python API - will actually reflect changes in visibility conditions which would be reflected by a script being installed or not after the dialog has been displayed), and the way that the SelectShortcut() function works will - quite simply - break if visibility conditions of the items its displaying changes as what it shows is based on the index of what has previously been selected. (though the explorer() function should handle this change without (too many) issues).

I wanted to get it out there, though, because it would be a great addition to the script and I don't want it to get forgotten. And I would also like to see it not taking a long time to get this onto the repo version, even if that means another - relatively quick - update.

Can I also take this opportunity to compliment you on the Default Widgets provided by the skin helper service. I normally pride myself on thinking through the various scenarios that the script will be used for, and doing my best to code for them in advance. In this case, though, I thought that the code that showed additional service widgets as the specific-media-types (e.g. skin.extendedinfo showing up under video add-ons) would be enough. It wouldn't have been and, without your additions, the new widgets wouldn't have been anywhere near as effective as they have been :)

(And, just to reflect how effective they have been - with your addition - there is no significant changes to the new widget code in what we're proposing for the new repo version. For something that was such a significant change both to this script and how skins interact with it, that's frankly amazing - and one of the big reasons for that is the widgets the skin helper service displays.)

Do you want me to update the readme/changelog to mark stable, or will you do that yourself before repo push?

TBH I'm kind of looking forward to being impressed by the lack of CPU/GPU of the skin helper script (let alone seeing what I can actually do with it!) Again, from the forum thread, it's clear you've taken this into account, and I'm sure it will extend my Conq mod in great, and non-intensive, ways :)

**Comment by marcelveldt** [comment]
Sounds good to me. Once we've updated the script (and first version of skinhelper) to the repo we can discuss this further. Would be kind of neat to present the user with a dialog if they want to install the addon.I think that it would be a relativel simple change in the skinhelper code. The only thing I don't know is if the selectdialog of skinshortcuts will be able to keep up. I will do a quick check if my theory is correct.

No need to give compliments on my side. You're the father of skinshortcuts script which is embraced by almost every skinner out there. Nice to see the 2 scripts working together to get a richer user experience. Thanks for your hard work!

I don't mind if I should update the readme/changelog myself. If you want to do it and have time for it go ahead. If you don't have time I will do so tomorrow.

**Comment by ghost** [comment]
The primary issue will be if the Kodi's select dialog respects changes to visibility conditions once the items have been sent to it. I'll be very interested to know what your test show! If not, a workaround will likely be relatively difficult. As I say, the SelectShortcut() function will also cause issues - but changing it from using the index of the item selected to (say) the action of the item selected (or a unique ID as we use when the menu is actually built) to decide which options have been selected on previous levels should be an relatively easy change and make it more robust ;)

(And, of course, the script will need some way to trigger a RunScript command - probably a variation of the ||BROWSE|| action used to switch between the SelectShortcut() and explorer() functions... - ||RUNSCRIPT|| for example)

But, as you say, this is something that can and should be discussed after a repo push.

Yes, there is need to give compliments on your side :) I might be the father of the script, but please don't underestimate what your integration of the skin helper service has brought. Honestly, the new widgets would have had far more complaints/requests and therefore script-modifications to get a feature set not nearly equivalent to what you have added if you hadn't integrated the skin helper script :) It also goes against one of my original decisions of the script - which was that no external script would get special treatment within Skin Shortcuts. Your integration of the skin helper script has proved that that wasn't the correct decision!

I'll leave you to update the readme/changelog if that's alright, as I've shut down my development systems for the weekend ;)

**Comment by ghost** [comment]
I've created #98 which I'll keep up to date with any necessary version bump + readme/chanelog changes ready for when script is to be pushed to repo :)

**Comment by marcelveldt** [comment]
OK, great. I have just submitted my request to add skinhelper to the Kodi repo. I will send the request for skinshortcuts tomorrow. Hopefully both scripts will then be updated/available at the same time on the repo.

**Comment by ghost** [comment]
Nice :)

My coding time is currently being taken up by a private project (where a daft PR was accepted, and we're all running around like headless chickens fixing things) with which most of my current coding time is focused, so it will be good to know that this script has been recently updated and, quite frankly, I can ignore it for a little while :)

Thanks for taking charge of the actual repo push!

**Comment by marcelveldt** [comment]
OK, skinhelper service just got added to the Kodi repo. I will now submit the 0.6.5 version to the Kodi repo. Note that this will be Isengard+ only

**Comment by marcelveldt** [comment]
@BigNoid I have just resent the request to update skinshortcuts on the repo. There seems to be a bug in the current stable version which is causing issues with your recent Aeon Nox skin. This issue is fixed on Git but now the Git version needs to be updated ASAP to the Kodi repo. Is there anything you can do to speed it up ?

**Comment by ghost** [comment]
Just a note, the bug isn't in the current stable version on the official repo (0.6.0). It was in the version requested to be updated to on the repo (though now fixed thanks to marcelveldts quick work) - 0.6.5. I'm guessing that its come to light because a 3rd party repo that the users reporting the issue have installed pushed the updated version to their repo.

**Comment by BigNoid** [comment]
I am out of the country atm, I can't push the fixed version myself her and I think there's only 1 team member handling all the addon (and skin) updates. So atm I can't be of much help, sorry.

**Comment by marcelveldt** [comment]
No problem, it turns out the bug isn't on official repo but on some 3th party repo version of the script. Ronie is going to push an update of the script this weekend so it will be okay.

**Comment by marcelveldt** [comment]
I have just bumped the version to 0.6.6 to make sure people get this new version and I hope that all skin devs who host their own copy of the script on their repo will be so kind so update it asap.

**Comment by ghost** [comment]
:+1: on the version bump :)

Does this need a new tag/release, so that the repo gets updated to 0.6.6...? (Not quite sure how it works with what version gets picked up)

**Comment by marcelveldt** [comment]
I asked Ronie to just pull the latest version from Git... Just to be safe I can also create a new tag

**Comment by ghost** [comment]
That's grand. I didn't know whether it was pulled from a specific tag, a specific commit or just 'latest version' ;)

(Just really don't want to be dealing with users on the same version number as official, but not official!)

**Comment by marcelveldt** [comment]
Ronie has just updated the 0.6.6 to the Kodi repo. Issue closed ;-)
